# Generated by Django 5.2.8 on 2026-07-29 11:03
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('system_manage', '0005_resourcemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='uid',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='UID'),
        ),
    ]
