# Generated by Django 5.2.13 on 2026-07-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_applicationversion_knowledge_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationlongtermmemory',
            name='last_extract_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次提取时间'),
        ),
    ]
